server:
  port: 8080 # El frontend (React) apuntará siempre a este puerto

spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 1. Tu configuración de CORS intacta
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" # En producción pones la URL de React
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            
      # 2. La palabra mágica para tu versión del Gateway
      mvc:
        routes:
          # Ruta hacia el Auth Service
          - id: auth-service
            uri: http://localhost:8081
            predicates:
              - Path=/auth/**
              
          # Ruta hacia el Ingestion Service (Transacciones)
          - id: ingestion-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/transactions/**
              
          # Ruta hacia el Dashboard Service (Métricas)
          - id: dashboard-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/dashboard/**